### ISSUE TITLE
idtr generator BUG

### ISSUE THREAD

**Issue by ryumada** [garasijogi/mosacc-backend#1]
idtr generator just count the record, so if there is any record deleted before not the last one, the generator will generate the same increment with the last record, so it makes the idtr not unique again.

**Comment by algorithmsEvolve** [comment]
Gua pernah ngalamin ini di ERP kelas kita ki, lu coba deh setiap lu nge input,sebelum input, idtr nya itu di cek dulu di db, ada ga di db yg idtr nya sama. kalo ada, angka terakhirnya ditambah 1, baru di input. Gua dulu kayak gini waktu bikin yg ERP.
