### ISSUE TITLE
assets wizard enhancment

### ISSUE THREAD

**Issue by algorithmsEvolve** [garasijogi/mosacc-backend#25]
- add unit quantity for assets wizard
- add date atribute and selector for assets wizard
- add brand on tools asset table
- change kas assets to kas bank assets
`nomor, nama, nomor rekening, nominal`

**Comment by ryumada** [comment]
[this commit](https://github.com/garasijogi/mosacc-backend/commit/70b48c4e0c7ca7cde6420ed6cf895c55c52f8f8d) fixed this issue.
