### ISSUE TITLE
aset form input in wizard

### ISSUE THREAD

**Issue by algorithmsEvolve** [garasijogi/mosacc-backend#40]
add input form for aset perlengkapan and aset kendaraan on wizard

**Comment by ryumada** [comment]
fixed on this [commit](https://github.com/garasijogi/mosacc-backend/commit/971b68de8b8cdd6541885d0a5c79c6d91d8ed127)

**Comment by ryumada** [comment]
I forgot @algorithmsEvolve must connect it to the report module, is that right?

**Comment by algorithmsEvolve** [comment]
@RizkiTH yeah, i will fix that as soon as possible

**Comment by ryumada** [comment]
You can import the `master` database from `Ryu` branch at Ryu folder

**Comment by algorithmsEvolve** [comment]
@RizkiTH hehe

**Comment by algorithmsEvolve** [comment]
i've done it!
